name: Deploy

on:
  push:
    branches: ['master', 'config_docker']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add key.pem
        run: echo "${{ secrets.SSH_KEY }}" > "key.pem"
      - name: Change mode
        run: chmod 400 "key.pem"
      - name: SSH
        run: |
          ssh -tt -i "key.pem" -o StrictHostKeyChecking=no ec2-user@ec2-3-25-253-64.ap-southeast-2.compute.amazonaws.com "
          rm -rf material-mastery-server &&
          git clone git@github.com:khang1010/material-mastery-server.git &&
          cd material-mastery-server && 
          sudo docker-compose down &&
          sudo docker-compose up --build -d &&
          sudo docker image prune -f &&
          exit
          "
